services:
  db:
    restart: always
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/logs
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
