basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a sample server celler server.
  title: Support API
  version: "5.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    description: Description for what is this security definition being used
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
